kapprovals/urls.py
from django.urls import path

from kapprovals import views


app_name = 'kapprovals'


urlpatterns = [
    path("execute/<int:approval_pk>/<int:level_ct_pk>/", views.ApprovalExecuteView.as_view(), name="approval_execute"),
    path("detail/<int:pk>/", views.ApprovalDetailView.as_view(), name="approval_detail"),

    path("approval/run/<int:read_site_pk>/<int:write_site_pk>/<int:level_ct_pk>/", views.RunApprovalView.as_view(),
         name="run_approval"),
    path("content/info/<int:read_site_pk>/<int:write_site_pk>/<int:level_ct_pk>/", views.ContentInfoView.as_view(),
         name="content_info"),
]

kapprovals/templates/kapprovals/includes/approval_issues.html
<table class="table table-bordered mb-0">
    <tbody>
    {% for x in issues %}
        <tr>
            <td class="py-2 px-3">
                {% for msg in x.message %}
                    {{ msg }}
                    {% if not forloop.last %}<hr />{% endif %}
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

kapprovals/templates/kapprovals/includes/single_approval_box.html
<table class="table table-bordered bg-white">
    <thead class="thead-grey bg-light">
        <tr>
            <th>{{ title }}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for obj in levels %}
        <tr>
            <td>
                {% if obj.action.can_run %}
                    <a href='{% url "kapprovals:run_approval" read_site.pk write_site.pk obj.level_content.pk %}?content_pks={{ content_pks }}'
                       class="text-center my-1 popup-window {{ obj.level.action_button_class }}"
                       id="id_level_{{ obj.level.pk }}">
                        {% if obj.level.action_icon_class %}
                            <i class="{{ obj.level.action_icon_class }}"></i>
                        {% endif %} &nbsp;
                        {{ obj.level.name }}
                    </a>
                    <br />
                    <small>{{ obj.level.description }}</small>
                {% else %}
                    <b>{{ obj.level.name }}</b>
                {% endif %}

                {% if obj.approval.date_completed %}
                    <p class="mb-0 font-weight-lighter small">
                        {{ obj.approval.get_completed_name }}
                        by <b>{{ obj.approval.completed_by }}</b>
                        at <b>{{ obj.approval.date_completed }}</b>
                    </p>
                {% else %}
                    {% if obj.level.summary %}
                        <p class="mb-0 font-weight-lighter small">{{ obj.level.summary }}</p>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                <a href='{% url "kapprovals:content_info" read_site.pk write_site.pk obj.level_content.pk %}?content_pks={{ content_pks }}'
                    class="btn btn-outline-secondary btn-sm popup-window" id="id_level_action_{{ obj.level.pk }}">
                    {% if obj.action.is_completed %}
                        <i class="fa fa-check-circle text-success"></i>
                    {% else %}
                        {% if obj.action.can_run %}
                            <i class="fa fa-info-circle text-primary"></i>
                        {% else %}
                            <i class="fa fa-exclamation-circle text-warning"></i>
                        {% endif %}
                    {% endif %}
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


<script type="text/javascript">
    document.querySelectorAll(".popup-window").forEach(function(elem) {
        elem.addEventListener("click", function(event){
            event.preventDefault();
            var url = this.getAttribute("href");
            var name = this.getAttribute("id");

            popupWindow(url, name, window, 500, 500);
        }, false);
    });

    function popupWindow(url, windowName, win, w, h) {
        const y = win.top.outerHeight / 2 + win.top.screenY - ( h / 2);
        const x = win.top.outerWidth / 2 + win.top.screenX - ( w / 2);
        return win.open(url, windowName, `toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=${w}, height=${h}, top=${y}, left=${x}`);
    }
</script>