kapprovals/urls.py
from django.urls import path

from kapprovals import views


app_name = 'kapprovals'


urlpatterns = [
    path("execute/<int:approval_pk>/<int:level_ct_pk>/", views.ApprovalExecuteView.as_view(), name="approval_execute"),
    path("detail/<int:pk>/", views.ApprovalDetailView.as_view(), name="approval_detail"),

    path("approval/run/<int:read_site_pk>/<int:write_site_pk>/<int:level_ct_pk>/", views.RunApprovalView.as_view(),
         name="run_approval"),
    path("content/info/<int:read_site_pk>/<int:write_site_pk>/<int:level_ct_pk>/", views.ContentInfoView.as_view(),
         name="content_info"),
]

kapprovals/models.py
import uuid
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from kapprovals.constants import VALUE_TYPES, OPERATORS


class BaseModel(models.Model):
    site = models.ForeignKey('sites.Site', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    guid = models.UUIDField(null=True, blank=True, unique=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.guid = self.guid or uuid.uuid4()
        return super(BaseModel, self).save(*args, **kwargs)


class Level(BaseModel):
    identifier = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250, null=True, blank=True)
    sort = models.IntegerField(default=0, help_text="Regular sorting")
    completed_name = models.CharField(null=True, blank=True, max_length=100,
                                      help_text="Text that appears after completing action")
    action_groups = models.ManyToManyField('auth.Group', blank=True, help_text="Groups which can perform this action")
    action_button_class = models.CharField(max_length=100, null=True, blank=True)
    action_icon_class = models.CharField(max_length=100, null=True, blank=True)
    color = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('sort',)
        unique_together = ('site', 'identifier')

    def get_completed_name(self):
        return self.completed_name or self.name


class LevelContent(BaseModel):
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.level}: {self.content_type}'

    def save(self, *args, **kwargs):
        self.site = self.level.site
        super().save(*args, **kwargs)

    class Meta:
        unique_together = ('site', 'level', 'content_type')
        ordering = ('content_type', 'level')

    def get_summary(self):
        return self.content_type.model.upper()


class LevelContentStep(BaseModel):
    level_content = models.ForeignKey(LevelContent, on_delete=models.CASCADE)
    related_level_content = models.ForeignKey(LevelContent, on_delete=models.CASCADE,
                                              related_name='relatedlevelcontent')
    step = models.IntegerField(default=0)
    is_required = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.level_content}: {self.related_level_content}'

    class Meta:
        unique_together = ('site', 'level_content', 'related_level_content')

    def save(self, *args, **kwargs):
        self.site = self.level_content.site
        super().save(*args, **kwargs)


class LevelContentCondition(BaseModel):
    level_content = models.ForeignKey(LevelContent, on_delete=models.CASCADE)
    field_name = models.CharField(max_length=50)
    operator = models.CharField(max_length=10, choices=OPERATORS, default='==')
    value = models.CharField(max_length=250, null=True, blank=True)
    value_type = models.CharField(max_length=10, choices=VALUE_TYPES, default='str')
    message = models.CharField(max_length=250)
    sort = models.IntegerField(default=1000)

    def __str__(self):
        return '%s %s' % (self.field_name, self.get_operator_display())

    class Meta:
        ordering = ('sort',)

    def save(self, *args, **kwargs):
        self.site = self.level_content.site
        super().save(*args, **kwargs)


# states: approved, deferred, cancelled
class Approval(BaseModel):
    guid = models.UUIDField()
    identifier = models.CharField(max_length=100)
    level_content = models.ForeignKey(LevelContent, on_delete=models.CASCADE)
    status = models.CharField(max_length=50)

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name='%(app_label)s%(class)s_created_by')
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                    related_name='%(app_label)s%(class)s_modified_by')
    completed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True,
                                     related_name='%(app_label)s%(class)s_completed_by')
    date_completed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return '%s %s' % (self.pk, self.level_content)

    class Meta:
        ordering = ('-date_created',)

    def save(self, *args, **kwargs):
        self.guid = self.guid or uuid.uuid4()
        return super().save(*args, **kwargs)


class ApprovalRoute(BaseModel):
    approval = models.ForeignKey(Approval, on_delete=models.CASCADE)
    related_approval = models.ForeignKey(Approval, on_delete=models.CASCADE, related_name='related_approval')
    date_completed = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ('site', 'approval', 'related_approval')


class ContentMeta(BaseModel):
    """
    This model is used to keep track per object. We want to track changes to level. It is especially useful for
    reporting. We track the actual change with datetime in the ApprovalContent model.
    """
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    content_object = GenericForeignKey()
    action = models.CharField(max_length=50)
    date_completed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.content_object)

    class Meta:
        unique_together = ('site', 'content_type', 'object_id')


class ApprovalContent(BaseModel):
    approval = models.ForeignKey(Approval, on_delete=models.CASCADE)
    content_meta = models.ForeignKey(ContentMeta, on_delete=models.CASCADE)
    action = models.CharField(max_length=50)
    note = models.CharField(max_length=250, null=True, blank=True)
    date_completed = models.DateTimeField(null=True, blank=True)
    completed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        unique_together = ('site', 'approval', 'content_meta')

    def get_completed_name(self):
        return self.approval.level_content.level.completed_name or self.action
    get_completed_name.short_description = "Completed name"

kapprovals/templates/kapprovals/approval_detail.html
{% extends "kapprovals/base.html" %}


{% block content %}

<div class="row">
<div class="col-md-8 offset-md-2">
    <div class="card rounded-0 shadow-sm mt-4">
        <div class="card-header bg-light">
            <h3>{{ approval.level_content.level }}</h3>
            <p class="mb-0">Status: {{ approval.status|upper }}</p>
        </div>
        <div class="card-body">

            {% for ctn in approval.approvalcontent_set.all %}
            <div>
                <small>{{ approval.level_content.content_type.model.title }}</small>
                <br />
                <h6>{{ ctn.content_object }}</h6>
                {% if ctn.content_object.get_absolute_url %}
                <a href="{{ ctn.content_object.get_absolute_url }}">View Details</a>
                {% endif %}
            </div>
            {% if not forloop.last %}<hr />{% endif %}
            {% endfor %}

        </div>
    </div>
</div>
</div>

    {% comment %}
    <h3>{{ approval.level_content.level }}</h3>
    <p>Status: {{ approval.status|upper }}</p>

    <table class="table table-bordered bg-white">
        <thead>
            <tr>
                <th>#</th>
                <th>Entry</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for ctn in approval.approvalcontent_set.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    {{ ctn.content_object }}
                </td>
                <td>
                    {% if ctn.content_object.get_absolute_url %}
                    <a href="{{ ctn.content_object.get_absolute_url }}">View Details</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endcomment %}

    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function(event) {
            {% if auto_close_popup %}
                closePopupWindow(true);
            {% endif %}
        });

        document.querySelector(".close-popup").addEventListener("click", function(event) {
            closePopupWindow();
        }, false);

        function closePopupWindow(refreshParent=false) {
            if (refreshParent)
                window.opener.location.reload(true);
            window.self.close();
        }
    </script>

{% endblock %}

kapprovals/templates/kapprovals/base.html
{% extends "admin/base.html" %}

kapprovals/templates/kapprovals/base_popup.html
<html>
	<head>
		<title>{{ head_title }}</title>
        {% block after_head %}{% endblock %}
	</head>
	<body>
		{% block content %} {% endblock %}

        {% block after_body %}{% endblock %}
	</body>
</html>

kapprovals/templates/kapprovals/content_info.html
{% extends "kapprovals/base_popup.html" %}


{% block content %}
    <h3>Info</h3>

    {% for levels in content_info.levels.values %}
    <table class="">
        {% for lvl in levels %}
        <tr>
            <td>
                {{ lvl.level }}<br />
                {{ lvl.approval }}
            </td>
            <td>
                {% include "kapprovals/includes/approval_issues.html" with issues=lvl.action.issues %}
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endfor %}

{% endblock %}

kapprovals/templates/kapprovals/run_approval.html
{% extends base_template %}


{% block content %}
    <h3>Confirmation</h3>
    <p>Are you sure you want to <b>{{ level_content.level.name }}?</b></p>

    <form action='{% url "kapprovals:run_approval" sites.read_site.pk sites.write_site.pk level_content.pk %}?content_pks={{ content.pks }}&pt={{ page_type }}'
          method="post">
        {% csrf_token %}

        <table class="table table-bordered bg-white">
            <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Entry</th>
                    <th>Note</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for content_object in content.queryset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <small>{{ level_content.content_type.model.title }}</small>
                        <br />
                        {{ content_object }}
                        {% if content_object.get_absolute_url %}
                            <br /><br />
                            <a href="{{ content_object.get_absolute_url }}" target="_blank">View Details</a>
                        {% endif %}
                    </td>
                    <td>
                        <input type="text" name="{{ content_object.pk }}__note" class="form-control" />
                    </td>
                    <td>
                        <select name="{{ content_object.pk }}__action">
                            <option value="accept">Accept</option>
                            <option value="reject">Reject</option>
                        </select>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <table class="table">
            <tr>
                <td style="width: 100%">
                    <a href="#" class="btn btn-danger close-popup">Cancel</a>
                </td>
                <td>
                    <input type="submit" class="btn btn-success" value="Proceed" />
                </td>
            </tr>
        </table>

    </form>

    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function(event) {
            {% if auto_close_popup %}
                closePopupWindow(true);
            {% endif %}
        });

        document.querySelector(".close-popup").addEventListener("click", function(event) {
            closePopupWindow();
        }, false);

        function closePopupWindow(refreshParent=false) {
            if (refreshParent)
                window.opener.location.reload(true);
            window.self.close();
        }
    </script>

{% endblock %}